[theme]
primaryColor = "#667eea"
backgroundColor = "#0f0f0f"
secondaryBackgroundColor = "#262630"
textColor = "#fafafa"
font = "sans serif"

[client]
showErrorDetails = true
showSidebarNavigation = true

[server]
maxUploadSize = 200
enableXsrfProtection = true
headless = true
port = 8501
baseUrlPath = "/"

[logger]
level = "info"
